apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: php
spec:
  type: LoadBalancer
  selector:
    app: php
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
