apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: bruno-dam/projeto-database:1.0
          imagePullPolicy: Always
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "Senha123"
          - name: MYSQL_DATABASE
            value: "meubanco"
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-dados
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-dados
          persistentVolumeClaim:
            claimName: mysql-dados

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: bruno-dam/projeto-backend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
